# Used by AWS CodeBuild

# gradlew needs chmod +x for it to be executed on CodeBuild
# https://www.scivision.dev/git-windows-chmod-executable/

version: 0.2
phases:
  build:
    on-failure: ABORT
    commands:
      - echo Building RooksAndWalls Application
      - ./gradlew test buildFatJar
artifacts:
  files:
    - build/libs/me.leonunes.rooksandwallsserver-all.jar
  discard-paths: yes