# Used by AWS CodeDeploy
# Reference:
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/application-revisions-appspec-file.html#add-appspec-file-server

version: 0.0
os: linux
files:
  - source: /
    destination: /opt/rooksandwalls/
  - source: /rooksandwalls.service
    destination: /lib/systemd/system
permissions:
  - object: /opt/rooksandwalls
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: /lib/systemd/system/rooksandwalls.service
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: /scripts/codedeploy/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: /scripts/codedeploy/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: /scripts/codedeploy/after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: /scripts/codedeploy/application_start.sh
      timeout: 30
      runas: root
#  ValidateService:
#    - location:
#      timeout:
#      runas: