# Used by AWS CodeDeploy
# Reference:
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/application-revisions-appspec-file.html#add-appspec-file-server

version: 0.0
os: linux
files:
  - source: /
    destination: /opt/games/
permissions:
  - object: /opt/games
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/codedeploy/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/codedeploy/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/codedeploy/after_install.sh
      timeout: 90
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/application_start.sh
      timeout: 30
      runas: root
#  ValidateService:
#    - location:
#      timeout:
#      runas: